version: "3.4"

services:
  app:
    image: recommendations-client
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["http-server", "build"]
    ports:
      - 3086:8080
    volumes:
      - ./:/app
