version: "3.4"

services:
  app:
    image: recommendations-client
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["serve", "-s", "build"]
    ports:
      - 3086:3000
    volumes:
      - ./:/app
